# Generated by Django 5.1.6 on 2025-05-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='some_field',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
