# Generated by Django 5.1.6 on 2025-05-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_some_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='some_field',
        ),
    ]
